version: '3.9'

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=myfirstdb
    volumes:
      - ./dbms-data:/var/lib/mysql
    networks:
      - sgbdr-network

networks:
  sgbdr-network:
    driver: bridge
